[package]
name = "thenexusavenger/module3d"
repository = "https://github.com/TheNexusAvenger/Module3D"
description = "Adorns 3D models in Roblox to frames."
license = "MIT"
authors = ["TheNexusAvenger"]
version = "6.3.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]